//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiColegio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacion
    {
        public int Id { get; set; }
        public int MateriaId { get; set; }
        public int EstudianteId { get; set; }
        public string NotaCualitativa { get; set; }
        public double NotaNumerica { get; set; }
        public byte Activo { get; set; }
    
        public virtual Materia Materia { get; set; }
        public virtual Estudiante Estudiante { get; set; }
    }
}
