//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiColegio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradoEnCurso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GradoEnCurso()
        {
            this.Materia = new HashSet<Materia>();
        }
    
        public int Id { get; set; }
        public int GradoId { get; set; }
        public int MaestroId { get; set; }
        public int SeccionId { get; set; }
        public int Año { get; set; }
        public byte Activo { get; set; }
    
        public virtual Grado Grado { get; set; }
        public virtual Maestro Maestro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materia> Materia { get; set; }
        public virtual Seccion Seccion { get; set; }
    }
}
