//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiColegio.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Matricula
    {
        public int Id { get; set; }
        public int TutorId { get; set; }
        public int EstudianteId { get; set; }
        public int GradoId { get; set; }
        public int PeriodoId { get; set; }
        public string CodigoMatricula { get; set; }
        public string Descripcion { get; set; }
        public string ColegioProcedencia { get; set; }
        public byte Repitente { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public int ColegioId { get; set; }
        
        [JsonIgnore]
        public virtual Tutor Tutor { get; set; }
        [JsonIgnore]
        public virtual Estudiante Estudiante { get; set; }
        [JsonIgnore]
        public virtual Grado Grado { get; set; }
        [JsonIgnore]
        public virtual Periodo Periodo { get; set; }
        [JsonIgnore]
        public virtual Colegio Colegio { get; set; }
    }
}
