//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiColegio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloColegioContainer : DbContext
    {
        public ModeloColegioContainer()
            : base("name=ModeloColegioContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Estudiante> Estudiantes { get; set; }
        public virtual DbSet<Maestro> Maestros { get; set; }
        public virtual DbSet<Matricula> Matriculas { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Rol> Roles { get; set; }
        public virtual DbSet<Permiso> Permisos { get; set; }
        public virtual DbSet<Tutor> Tutores { get; set; }
        public virtual DbSet<Grado> Grados { get; set; }
        public virtual DbSet<Seccion> Secciones { get; set; }
        public virtual DbSet<Materia> Materias { get; set; }
        public virtual DbSet<Calificacion> Calificaciones { get; set; }
        public virtual DbSet<Periodo> Periodos { get; set; }
        public virtual DbSet<GradoEnCurso> GradosEnCursos { get; set; }
        public virtual DbSet<Colegio> Colegios { get; set; }
    }
}
