//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiColegio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Id { get; set; }
        public int RolId { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string NombreDeUsuario { get; set; }
        public string ClaveUsuario { get; set; }
        public string CorreoRecuperacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public byte Activo { get; set; }
        public int ColegioId { get; set; }
    
        public virtual Rol Rol { get; set; }
        public virtual Colegio Colegio { get; set; }
    }
}
